spring:
  mvc:
    static-path-pattern: '/static/**'
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true

toss:
  secret: test_sk_yL0qZ4G1VO1G4bBW4dMO8oWb2MQY
